# Generated by Django 5.2.14 on 2026-06-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_turno_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='nueva_fecha_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('REPROGRAMACION_PENDIENTE', 'Reprogramación Pendiente')], default='PENDIENTE', max_length=30),
        ),
        migrations.AlterField(
            model_name='turno',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
    ]
