# Generated by Django 5.2.14 on 2026-06-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_turno_nueva_fecha_hora_alter_turno_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADO', 'Aceptado'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('FINALIZADO', 'Finalizado'), ('REPROGRAMACION_PENDIENTE', 'Reprogramación Pendiente')], default='PENDIENTE', max_length=30),
        ),
    ]
